# generated by datamodel-codegen:
#   filename:  auth.schema.deref.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional
from .meta_dto import Meta, PipelineStep

class AuthType(Enum):
    form = "form"
    api_token = "api_token"

class Method(Enum):
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    PATCH = "PATCH"
    DELETE = "DELETE"

class RedirectPolicy(Enum):
    follow = "follow"
    error = "error"
    ignore = "ignore"

@dataclass
class AuthRequest:
    method: Method
    endpoint: str
    headers: Optional[Dict[str, str]] = field(default_factory=lambda: {})
    timeout_s: Optional[float] = None
    redirect_policy: Optional[RedirectPolicy] = RedirectPolicy.follow

@dataclass
class CsrfSpec:
    enabled: bool
    source_url: Optional[str] = None
    token_selector: Optional[str] = None
    token_field_name: Optional[str] = None

class CheckType(Enum):
    status_code = "status_code"
    header_present = "header_present"
    body_not_contains = "body_not_contains"

@dataclass
class SuccessCheck:
    check_type: CheckType
    params: Dict[str, Any]

@dataclass
class ApiTokenSpec:
    enabled: bool
    token_header: Optional[str] = None
    token_value: Optional[str] = None

@dataclass
class Profile:
    profile_id: str
    auth_type: AuthType
    request: Optional[AuthRequest] = None
    form_fields: Optional[Dict[str, Any]] = None
    csrf: Optional[CsrfSpec] = field(default_factory=lambda: {"enabled": False})
    success_checks: Optional[List[SuccessCheck]] = field(default_factory=lambda: [])
    api_token: Optional[ApiTokenSpec] = field(
        default_factory=lambda: {"enabled": False}
    )

@dataclass
class AuthConfigV1Min:
    meta: Meta
    profiles: List[Profile]