# generated by datamodel-codegen:
#   filename:  export.schema.deref.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional
from .meta_dto import Meta, PipelineStep

class Align(Enum):
    left = "left"
    center = "center"
    right = "right"
    justify = "justify"

class Valign(Enum):
    top = "top"
    vcenter = "vcenter"
    bottom = "bottom"

@dataclass
class Header:
    bold: Optional[bool] = None
    align: Optional[Align] = None
    valign: Optional[Valign] = None
    bg_color: Optional[str] = None
    font_color: Optional[str] = None
    border: Optional[int] = None
    text_wrap: Optional[bool] = None

@dataclass
class Cell:
    align: Optional[Align] = None
    valign: Optional[Valign] = None
    border: Optional[int] = None
    text_wrap: Optional[bool] = None

@dataclass
class SheetStyles:
    header: Header
    cell: Cell
    freeze_header: bool
    autowidth: bool

@dataclass
class ExportProfile:
    profile_id: str
    filename_pattern: str
    sheet_name_max_len: int
    sheet_name_core_limit: int
    multiple_sheets: bool
    sheet_styles: SheetStyles
    empty_sheet_name: str

@dataclass
class ExportConfigV1:
    meta: Meta
    profiles: List[ExportProfile]