# generated by datamodel-codegen:
#   filename:  logging.schema.deref.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional
from .meta_dto import Meta, PipelineStep

class LogLevel(Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

@dataclass
class LogbusSpec:
    queue_max_size: int
    drain_batch_limit: int
    drop_oldest: bool

@dataclass
class UiSpec:
    log_buffer_max_lines: int
    batch_pull: int
    render_limit: int
    poll_interval_ms: int
    level: LogLevel

@dataclass
class EventsPolicy:
    levels: List[LogLevel]
    aggregate_batch_summary: bool
    include_context: bool

@dataclass
class LoggingProfile:
    profile_id: str
    logbus: LogbusSpec
    ui: UiSpec
    events: EventsPolicy

@dataclass
class LoggingConfigV1:
    meta: Meta
    profiles: List[LoggingProfile]