# generated by datamodel-codegen:
#   filename:  manifest.schema.deref.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional

Semver = str

VersionConstraint = str

class ConfigType(Enum):
    pipeline = "pipeline"
    site = "site"
    url = "url"
    network = "network"
    auth = "auth"
    logging = "logging"
    export = "export"

Path = str

@dataclass
class ConfigEntry:
    type: ConfigType
    config_id: str
    path: Path
    expected_version: VersionConstraint

@dataclass
class ManifestMeta:
    manifest_id: str
    version: Semver
    created_at: str
    description: Optional[str] = ""
    tags: Optional[List[str]] = field(default_factory=lambda: [])

@dataclass
class ConfigmanifestV1:
    manifest_meta: ManifestMeta
    configs: List[ConfigEntry]