# generated by datamodel-codegen:
#   filename:  meta.schema.deref.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional


class PipelineStep(Enum):
    pipeline = "pipeline"
    site = "site"
    url = "url"
    network = "network"
    auth = "auth"
    logging = "logging"
    export = "export"


@dataclass
class Meta:
    pipeline_step: PipelineStep
    config_id: str
    version: str
    description: Optional[str] = ""
    tags: Optional[List[str]] = field(default_factory=lambda: [])
    active_profiles: Optional[List[str]] = field(default_factory=lambda: [])
