# generated by datamodel-codegen:
#   filename:  network.schema.deref.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Union
from .meta_dto import Meta, PipelineStep

class NetworkSession:
    connect_timeout_s: float
    read_timeout_s: float
    write_timeout_s: float
    max_connections: int
    max_keepalive_connections: int
    http2: bool
    default_headers: Dict[str, str]
    verify_tls: bool
    base_url: Optional[str] = None
    request_timeout_s: Optional[float] = None
    ca_path: Optional[str] = None

class RetryOnExceptionsCategoryEnum(Enum):
    timeout = "timeout"
    network = "network"
    connection = "connection"

@dataclass
class RetryPolicy:
    max_attempts: int
    initial_delay_s: float
    backoff_multiplier: float
    max_delay_s: float
    timeout_budget_s: float
    retry_on_status: List[Union[int, str]]
    retry_on_exceptions_category: List[RetryOnExceptionsCategoryEnum]
    retry_non_idempotent: Optional[bool] = False

@dataclass
class RateLimit:
    enabled: bool
    requests_per_second: int
    burst_size: int
    jitter_s: float

@dataclass
class NetworkProfile:
    profile_id: str
    concurrency: int
    session: NetworkSession
    retry_policy: RetryPolicy
    rate_limit: RateLimit

@dataclass
class NetworkConfigV1:
    meta: Meta
    profiles: List[NetworkProfile]