# generated by datamodel-codegen:
#   filename:  pipeline.schema.deref.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional
from .meta_dto import Meta, PipelineStep

class Profile:
    profile_id: str
    batch_size: int

@dataclass
class PipelineConfigV1:
    meta: Meta
    profiles: List[Profile]