# generated by datamodel-codegen:
#   filename:  site.schema.deref.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional
from .meta_dto import Meta, PipelineStep

class Extract(Enum):
    text = "text"
    attr = "attr"

@dataclass
class ValueSelector:
    selector: str
    extract: Extract
    attr: Optional[str] = None

@dataclass
class NormalizeStep:
    tool: str
    params: Optional[Dict[str, Any]] = field(default_factory=lambda: {})

@dataclass
class FieldSpec:
    name: str
    value_selectors: List[ValueSelector]
    is_unique: Optional[bool] = False
    missing_as_error: Optional[bool] = True
    normalize_pipeline: Optional[List[NormalizeStep]] = field(
        default_factory=lambda: []
    )

@dataclass
class ItemContainer:
    container_id: str
    item_selectors: List[str]
    fields: List[FieldSpec]

@dataclass
class SiteProfile:
    profile_id: str
    page_container_selector: str
    item_containers: List[ItemContainer]

@dataclass
class SiteConfigV1:
    meta: Meta
    profiles: List[SiteProfile]