# generated by datamodel-codegen:
#   filename:  url.schema.deref.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Union
from .meta_dto import Meta, PipelineStep

class Action(Enum):
    add_params = "add_params"
    remove_params = "remove_params"
    normalize_slash = "normalize_slash"
    replace_host = "replace_host"
    strip_fragment = "strip_fragment"

class Scheme(Enum):
    http = "http"
    https = "https"

@dataclass
class UrlCondition:
    host: Optional[str] = None
    path_regex: Optional[str] = None
    has_param: Optional[str] = None
    scheme: Optional[Scheme] = None

@dataclass
class UrlRule:
    condition: UrlCondition
    action: Action
    params: Optional[Union[Dict[str, Any], List[Any]]] = field(
        default_factory=lambda: {}
    )
    priority: Optional[int] = 100

@dataclass
class UrlProfile:
    profile_id: str
    rules: List[UrlRule]

@dataclass
class UrlConfigV1:
    meta: Meta
    profiles: List[UrlProfile]